### ISSUE TITLE
rename package to binomen perhaps

### ISSUE THREAD

**Issue by sckott** [ropensci/taxa#13]
from #6

**Comment by sckott** [comment]
waiting on this until #12

**Comment by zachary-foster** [comment]
Is the main reason for doing this the name conflict with the `taxa` class? I am OK with changing it to `binomen`, but I like `taxa` better since it is shorter and more immediately understandable.

**Comment by sckott** [comment]
A few reasons. yes, fxn conflict, `taxa_` could become `taxa` - also pkg names that are too common of a word are hard to find on the internet, e.g., `taxa` results in 2.9 million hits on google scholar, while only 4000 for `binomen`

do you feel strongly about sticking with `taxa`?

**Comment by zachary-foster** [comment]
Ahh, yea, did not consider searchability.  Thats a good point. 

No, I don't feel strongly about `taxa`, I just kinda liked its simplicity, but searchability is more important.

**Comment by sckott** [comment]
sounds like we'll stick with `taxa`, so closing this
