### ISSUE TITLE
Add proper MIT License in LICENSE file

### ISSUE THREAD

**Issue by zachary-foster** [ropensci/taxa#150]
This was a suggestion from a reviewer of the taxa paper in F1000.

**Comment by sckott** [comment]
yeah, it's tough one because CRAN wants the dumb one that all R pkgs have, but then if you add another license file (e.g., `LICENSE-MIT` or similar) github i think will then just give up cause it doesn't know which license file to use

**Comment by zachary-foster** [comment]
Hmm, ok, thanks for the info. I don't know much about this. I don't think it is essential though; the reviewer said it was a "minor issue"

**Comment by sckott** [comment]
I agree that i wish we could have a proper license file and for github to detect it so it shows up in the top license info thingy, we should look around and see if there's any solution

**Comment by peterdesmet** [comment]
Does CRAN look at the LICENSE file (where GitHub looks) or in the license attribute in the DESCRIPTION?

https://github.com/ropensci/taxa/blob/daf5b84ea33cfd85f814d1a114a010662d394bb2/DESCRIPTION#L21

Was also wondering (for our packages), if "MIT + file LICENSE" is a recommended practice?

**Comment by zachary-foster** [comment]
I think it looks at the DESCRIPTION. It looks like we have it set up the way CRAN wants: 

https://cran.r-project.org/web/licenses/MIT

Its a bit cryptic, but the "MIT + file LICENSE" is mentioned

**Comment by peterdesmet** [comment]
Hmm, so where does the license text from that template go? Because that text would get it recognized by GitHub.

**Comment by zachary-foster** [comment]
It the LICENSE file required by CRAN? Can we add it .Rbuildignore and put what we want in it?

**Comment by sckott** [comment]
yes, that format i'm pretty sure is what they want

```
YEAR: 2018
COPYRIGHT HOLDER: Jane Doe
```

**Comment by zachary-foster** [comment]
I think we will have to leave it the way it is to keep CRAN happy. Sorry @peterdesmet! Good idea though
