### ISSUE TITLE
Package size NOTE

### ISSUE THREAD

**Issue by zachary-foster** [ropensci/taxa#166]
@sckott, any idea how to deal with this? IT only happens on Travis. Everything passes on the R cmd check on my computer. 

```
* checking installed package size ... NOTE
  installed size is  5.4Mb
  sub-directories of 1Mb or more:
    data   1.9Mb
    doc    2.8Mb
```

Where/What is this mysterious `doc` directory?

This does not agree with what the installed size is for me:

```
fosterz@fosterz-XPS-13-9343:~/R/x86_64-pc-linux-gnu-library/3.4/taxa$ du -h
32K	./Meta
20K	./html
328K	./help
24K	./ignore
760K	./R
992K	./data
2.2M	.

```

**Comment by sckott** [comment]
yeah, I get those notes on some of my pkgs as well. i believe `doc` is a folder created on pkg build, the tar.gz file from cran for taxa

```
➜  taxa tree -L 2 inst
inst
├── doc
│   ├── taxa-vignette.R
│   ├── taxa-vignette.Rmd
│   └── taxa-vignette.html
```

**Comment by zachary-foster** [comment]
Do you think it will make CRAN unhappy?

**Comment by sckott** [comment]
I don't think so, esp if it doesn't show up on winbuilder

**Comment by zachary-foster** [comment]
ok, thanks! I think I will ignore it for now then
