### ISSUE TITLE
Behavior of taxmap$func() vs func(taxmap)

### ISSUE THREAD

**Issue by zachary-foster** [ropensci/taxa#19]
@sckott, currently, I have set up the two ways of calling functions to behave differently.
Calling a function in the classical R way imitates traditional no-side-effects copy-on-change behavior by cloning the object before returning the changed clone version. For example, `filter_taxa(ex_taxmap, 1:3)` will not change `ex_taxmap`, but `ex_taxmap$filter_taxa(1:3)` will. Both return the modified `ex_taxmap`. 

Do you like this convention, or do you think it will confuse users? I suspect that each user will pick the style of calling they like and stick to it for the most part.

**Comment by sckott** [comment]
I agree that any one person will likely stick to one way or the other. 

I think we should stick with what you've done for now - we should get others to take a look at the entire package soonish and if there's a strong feeling about changes, we can talk about that then

**Comment by zachary-foster** [comment]
Sounds good

**Comment by zachary-foster** [comment]
Do we still want to have others weigh in on this? I can ask a few coworkers.

**Comment by sckott** [comment]
yeah, that'd be great

**Comment by zachary-foster** [comment]
Hey @knausb and @Tabima, would you mind weighing in on this if you have time? Thanks!

**Comment by zachary-foster** [comment]
Oh yea, and we would of course like to hear from @grunwald as well.

**Comment by knausb** [comment]
I think its great that you have engineered both behaviours!  I think that will make the package approachable to those of us who have a more more 'base R' perspective as well as those who want the side effects version.

**Comment by grunwald** [comment]
I agree with all comments and support the dual approach.

**Comment by zachary-foster** [comment]
Think we can close this or do we want more input?

**Comment by sckott** [comment]
i think we can close

**Comment by zachary-foster** [comment]
Cool
