### ISSUE TITLE
`taxa`: way to do operations on objects within it

### ISSUE THREAD

**Issue by sckott** [ropensci/taxa#196]
@zachary-foster 

in `taxize` i'm trying to use `taxa`, and currently doing  (pseudocode)

```r
output <- taxa::taxa(.list = lapply(res, function(z) {
    taxa::taxon(z, ...) # add data
}))
```

`taxa` is just a list, so users then can't do any operations over the output. 

wondering if i'm missing some way that one can manipulate all the taxon objects within the taxa class?  or if not, maybe we could make something here, or if not a good fit, then I can in taxize

e.g., `output$get_ids()` to extract all ids, and similar for names, etc.

**Comment by zachary-foster** [comment]
Hi @sckott, yeas the classes besides `taxonomy` and `taxmap` need some attention. They don't have getters/setters for the most part. 

I was working on that in #139, but I think that progress is on a stale branch somewhere. Perhaps its time to prioritize that a bit more.

**Comment by sckott** [comment]
cool, i'll close this in favor of #139 - what branch is it?

**Comment by zachary-foster** [comment]
Its on "s3_to_r6". Looks like I might of had the code for `taxa` working

**Comment by sckott** [comment]
ok, thanks
