### ISSUE TITLE
What do we need to get done before CRAN?

### ISSUE THREAD

**Issue by zachary-foster** [ropensci/taxa#35]
I figured we should work out exactly what we want done before submitting to CRAN. Is there a milestone for this? Is the v0.1 milestone the CRAN release?

**Comment by sckott** [comment]
yep, `v0.1` , will have a think

**Comment by sckott** [comment]
pushed date for milestone to may 4 for now, but can change as needed  https://github.com/ropenscilabs/taxa/milestone/1

**Comment by zachary-foster** [comment]
I am pretty much done with what I want for the first CRAN release. There are a few issues for `metacoder` that I am waiting on addressing until I migrate to `taxa`. In particular, I am anxious to address some issues of import/export of data since it is currently the largest deficiency of `metacoder` and is limiting its usage. How much more do you want to do before CRAN on your end?

**Comment by sckott** [comment]
@zachary-foster awesome. sounds good

There's a set of functions i want to bring over from `binomen` - we've got a few in so far - maybe it makes sense to just finish off implementing the ones i'm already working on and then bring in the rest later. sound good?  

hopefully i can finish that up this week 

then we can submit, and work on that blog post about all taxonomy pkgs to get out soon :)

**Comment by zachary-foster** [comment]
>just finish off implementing the ones i'm already working on and then bring in the rest later. sound good?

Yea, that sounds good to me. 

>work on that blog post about all taxonomy pkgs to get out soon 

Cool!

**Comment by zachary-foster** [comment]
This seems done too
