### ISSUE TITLE
Finalize function and option names

### ISSUE THREAD

**Issue by zachary-foster** [ropensci/taxa#38]
If we want to rename any functions or arguments, we should do that before CRAN. If there are options that do similar things between functions we should make sure they are the same. 

Standardizing the vocabulary we use in the man pages and vignettes is part of this too. For example, I tend to describe taxonomic ranks as "levels" sometimes or I use "parent taxa" and "supetaxa" the same way. I think this might confuse people who are new to these concepts, so I think we should pick one and stick to it. We could even add a glossary in the man pages and link words like "supertaxa" in other man pages to it?

**Comment by sckott** [comment]
> If we want to rename any functions or arguments, we should do that before CRAN

true , agree

> We could even add a glossary

sounds good

**Comment by zachary-foster** [comment]
Cool, I will start thinking about a glossary. Do you have any suggestions on how to implement that? It would be nice if it were all on the same page, but possible to link to specific terms. I could not find anything with a quick Google search on how to do that in a man page.

**Comment by sckott** [comment]
like this should work:

```r
#' Title of page
#'
#' @name man-page-name
#' ... whatever sections/bits you want
#' @examples
#' x <- foobar()
NULL
```

**Comment by zachary-foster** [comment]
Once you have all the functions from binomen that you want for the first CRAN release, do you want to work on this while on skype (or some other service where we can see the same screen) or over the phone? I figure we could do this all at once by going through each function and option in the package index. I think most the names are pretty good, but there are a couple I am not sure about how intuitive they are, but its hard for me to tell since I have been thinking about them so long.

**Comment by sckott** [comment]
Yeah, sounds good!, let's do that, can call over slack too

**Comment by zachary-foster** [comment]
I think this has been done
