### ISSUE TITLE
compliance with new dplyr version?

### ISSUE THREAD

**Issue by sckott** [ropensci/taxa#39]
hey @zachary-foster - have you checked that this pkg works with the new version of dplyr coming out on 11 May?

I haven't yet

https://github.com/tidyverse/dplyr

**Comment by zachary-foster** [comment]
No I haven't. Good idea

**Comment by sckott** [comment]
tested with new version installed, tests and examples all work, checks are good. will push up to travis installing new version to see if ok on ubuntu

**Comment by zachary-foster** [comment]
Nice!
