### ISSUE TITLE
Issue errors if a user tries to uses a `taxmap` option with `taxonomy` object

### ISSUE THREAD

**Issue by zachary-foster** [ropensci/taxa#47]
There are 4 functions that have been moved from `taxmap` to `taxonomy`:

- [x] filter_taxa
- [x] arrange_taxa
- [x] sample_n_taxa
- [x] sample_frac_taxa

These have a few options specific to taxmap. For the purposes of DRY, I will try to have the full functions in `taxonomy` and check the class used before allowing the options specific to `taxmap` to be used.

**Comment by sckott** [comment]
this is for first CRAN push, yes?

**Comment by zachary-foster** [comment]
I think so, I expect to have it done today. Now there is only one version of those functions in `Taxonomy` (not in `Taxmap`), so its actually a little less complicated than overwriting the functions in `taxmap` like I did originally. Just need to move things around and add some `if`s and `warnings`.

**Comment by sckott** [comment]
okay, will mark with the milestone
