### ISSUE TITLE
Go through docs right before CRAN

### ISSUE THREAD

**Issue by zachary-foster** [ropensci/taxa#54]
I am noticing some outdated and inconsistent documentation. 
We should probably go through it before the CRAN submission, although I fixed some of it.

**Comment by sckott** [comment]
👍  will also do for the bits I've been maintaining

**Comment by zachary-foster** [comment]
Cool

Do you use the roxygen comment re-flowing tool (ctrl+shift+/ in rstudio)? I was using it and noticing that is messes up the indentation of the usage examples. I could not use the `@usage` thing because R cmd check complains about our weird R6/S3 hybrid tactics, so I imitated the `@usage` section in the description. Just an FYI. If you select the text you want to re flow instead of just putting the cursor there it will leave the rest alone.

**Comment by sckott** [comment]
I don't use the reflow thing, didn't know about it. do you think i should?

**Comment by zachary-foster** [comment]
If you want, I like it when it does not mess stuff up. 
If you just put the cursor in a roxygen block it reflows the whole block, but if you select text, it only reflows that selection. I like using it right after I (re)write a section, but doing the whole block can mess stuff up if you have some custom indentation. 
I just mention it because it was messing up our custom formatting when I was using it and I just that out.
