### ISSUE TITLE
Add `branches` function

### ISSUE THREAD

**Issue by zachary-foster** [ropensci/taxa#56]
In the group of functions `roots`, `stems`, and `leaves` I think there is a place for everything else, which I was thinking about calling `branches`.

There is already an `is_branch` function, so I figure there could be a `branches` function to make things consistent. It would return info on everything that is not a root, stem, or leaf. The four together would be the whole tree.

**Comment by sckott** [comment]
sounds good, can you give an example of what a branch would be?

**Comment by zachary-foster** [comment]
A branch is anything that is not a root, stem, or, leaf. Its the interior of the tree after the first split starting from the roots. I am not sure if its really all that useful, but I like completing the metaphor and it should be easy to implement, since I could program it as any taxa not returned by  `roots()`, `stems()`, or `leaves()`.

**Comment by sckott** [comment]
right, does make sense to complete the set
