### ISSUE TITLE
fxn name conflicts

### ISSUE THREAD

**Issue by sckott** [ropensci/taxa#6]
there are two:
- for `taxa` classes we talked about using `hierarchies`, but there is already a `hierarchies` fxn for `taxmap` classes - currently i'm using `hierarchies_` for the version for `taxa` classes
- for the function `taxa` for `taxa` classes, the pkg is named `taxa`, so i'm using `taxa_` right now

thoughts on what to do? probably best to rename these things. 

One option is to simply merge `binomen` and `taxa` packages under the package name `binomen` - that means the classes in `binomen` are swept away, and we use the manipulation methods there for manipulating `taxa` classes, and there's no collision i don't think with `taxmap` classes

**Comment by zachary-foster** [comment]
> for taxa classes we talked about using hierarchies, but for taxa classes we talked about using hierarchies, but...

I actually just addressed this in my PR before even seeing this issue

> for the function taxa for taxa classes, the pkg is named taxa, so i'm using taxa_ right now

Yea, I was thinking about that too. I think the package should be renamed since `taxa` is such a good name for a class.  The best new package name I came up with is `taxar`, which is  OK, but not great.

> One option is to simply merge binomen and taxa packages  

I would be fine with that.

**Comment by sckott** [comment]
Saw the PR, thanks

I think merging into binomen is ideal, esp since there are already parsing/etc. methods for taxmap classes, and no equivalent for taxa classes. `dplyr` is needed for taxmap methods, and also for binomen methods, so we're not adding additional heavy dependencies

**Comment by zachary-foster** [comment]
Sounds good to me

**Comment by zachary-foster** [comment]
In order to maintain the issue and commit history of this repo, what do you think of merging the code of the current `binomen` and renaming this repo to `binomen`?

**Comment by sckott** [comment]
I do want to retain commit history for both - i'll google around how best to do the merge

**Comment by zachary-foster** [comment]
That would be great if that is possible

**Comment by sckott** [comment]
i think we can close this now, since just porting over some verb like methods from `binomen`

still not sure if we need/should change `taxa_` or not
