### ISSUE TITLE
What to do with cases with no data/results

### ISSUE THREAD

**Issue by sckott** [ropensci/taxa#95]
e.g., when using taxize, a user will often have some taxa with matches and some with no matches. We then have to turn the results into `taxa` pkg classes. Right now `taxa` classes can't do no data unless pass in e.g,. empty string  like `""` - 

maybe we should explicitly handle this so that "null" classes are supported and are supported when combining classes, etc. (supported could mean for null objects that they are dropped or something, not sure yet)

**Comment by zachary-foster** [comment]
Yea, something to think about. This is related to #90.

**Comment by sckott** [comment]
thx, yep, def. related

**Comment by zachary-foster** [comment]
oops, did not mean to close
